export const categories = [
    { id: "shawarma", label: "Shawarma", emoji: "🌯" },
    { id: "kids", label: "Kids menu", emoji: "🧒" },
    { id: "sauces", label: "Sauces", emoji: "🥫" },
    { id: "sandwiches", label: "Sandwiches", emoji: "🥪" },
    { id: "salads", label: "Salads", emoji: "🥗" },
];

export const styles = {
    header: {
        backgroundColor: "#8B0000",
        display: "flex",
        alignItems: "center",
        padding: "0 12px",
        height: "64px",
        gap: "10px",
        width: "100%",
        boxSizing: "border-box",
    },
    logoCircle: {
        width: 48,
        height: 48,
        borderRadius: "50%",
        backgroundColor: "#c0392b",
        border: "2px solid #fff",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    logoInner: {
        textAlign: "center",
        lineHeight: 1,
    },
    logoTop: {
        fontSize: 7,
        fontWeight: 900,
        color: "#fff",
        letterSpacing: "1.5px",
        display: "block",
    },
    chefIcon: {
        fontSize: 18,
        display: "block",
    },
    logoTextWrap: {
        display: "flex",
        flexDirection: "column",
        lineHeight: 1,
    },
    logoSub: {
        fontSize: 11,
        color: "#fff",
        fontWeight: 400,
        letterSpacing: "0.5px",
    },
    logoMain: {
        fontSize: 15,
        fontWeight: 700,
        color: "#fff",
        fontStyle: "italic",
    },
    menuBtn: {
        display: "flex",
        flexDirection: "column",
        gap: 4,
        cursor: "pointer",
        padding: "6px",
        background: "none",
        border: "none",
    },
    menuBar: {
        display: "block",
        width: 22,
        height: 2,
        backgroundColor: "#fff",
        borderRadius: 2,
    },
    menuLabel: {
        fontSize: 10,
        color: "#fff",
        textAlign: "center",
        marginTop: 2,
        letterSpacing: "0.5px",
    },
    searchWrap: {
        flex: 1,
        display: "flex",
        alignItems: "center",
        backgroundColor: "#fff",
        borderRadius: 20,
        padding: "0 12px",
        height: 36,
        gap: 8,
        minWidth: 0,
    },
    searchInput: {
        flex: 1,
        border: "none",
        outline: "none",
        fontSize: 13,
        color: "#333",
        background: "transparent",
        minWidth: 0,
    },
    navActions: {
        display: "flex",
        alignItems: "center",
        gap: 2,
        flexShrink: 0,
    },
    navBtn: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 2,
        padding: "4px 8px",
        background: "none",
        border: "none",
        cursor: "pointer",
        color: "#fff",
        minWidth: 48,
    },
    navBtnLabel: {
        fontSize: 10,
        color: "#fff",
        letterSpacing: "0.3px",
    },
};